version: '3.3'
services:
  tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
      - 8080:8080
    networks:
      - tyk
    volumes:
      - ./tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
      - ./policies:/opt/tyk-gateway/policies
    env_file:
      - tyk.env  
    depends_on:
      - tyk-redis
  # tyk-dashboard:
  #   image: tykio/tyk-dashboard
  #   ports: 
  #     - 8004:8080
  tyk-redis:
    image: redis:6.2.7-alpine
    networks:
      - tyk
    ports:
      - 6379:6379

networks:
  tyk:
